export interface BookEntry {
  title: string;
  chapters: string[];
}

export const BOOK_KNOWLEDGE_BASE: Record<string, string[]> = {
  // ─────────────────────────────────────────────
  // RUSSIAN CLASSICS
  // ─────────────────────────────────────────────
  "gulag archipelago": [
    "Part I: The Prison Industry — Ch.1: Arrest",
    "Part I: The Prison Industry — Ch.2: The History of Our Sewage Disposal System",
    "Part I: The Prison Industry — Ch.3: The Interrogation",
    "Part I: The Prison Industry — Ch.4: The Bluecaps",
    "Part I: The Prison Industry — Ch.5: First Cell, First Love",
    "Part I: The Prison Industry — Ch.6: That Spring",
    "Part I: The Prison Industry — Ch.7: In the Engine Room",
    "Part I: The Prison Industry — Ch.8: The Law as a Child",
    "Part I: The Prison Industry — Ch.9: The Law Becomes a Man",
    "Part I: The Prison Industry — Ch.10: The Law Matures",
    "Part I: The Prison Industry — Ch.11: The Supreme Measure",
    "Part I: The Prison Industry — Ch.12: Tyurzak",
    "Part II: Perpetual Motion — Ch.1: The Ships of the Archipelago",
    "Part II: Perpetual Motion — Ch.2: The Ports of the Archipelago",
    "Part II: Perpetual Motion — Ch.3: The Slave Caravans",
    "Part II: Perpetual Motion — Ch.4: From Island to Island",
    "Part III: The Destructive-Labor Camps — Ch.1: The Fingers of Aurora",
    "Part III: The Destructive-Labor Camps — Ch.2: The Archipelago Rises from the Sea",
    "Part III: The Destructive-Labor Camps — Ch.3: The Archipelago Metastasizes",
    "Part III: The Destructive-Labor Camps — Ch.4: The Archipelago Hardens",
    "Part III: The Destructive-Labor Camps — Ch.5: What the Camps Produced",
    "Part III: The Destructive-Labor Camps — Ch.6: How People Lived There",
    "Part III: The Destructive-Labor Camps — Ch.7: The Ways of Life and Customs of the Natives",
    "Part III: The Destructive-Labor Camps — Ch.8: Women in Camp",
    "Part III: The Destructive-Labor Camps — Ch.9: The Trusties",
    "Part III: The Destructive-Labor Camps — Ch.10: In Place of Politics",
    "Part III: The Destructive-Labor Camps — Ch.11: The Loyalists",
    "Part III: The Destructive-Labor Camps — Ch.12: Knights of the White Goose",
    "Part III: The Destructive-Labor Camps — Ch.13: Hand Over Your Heart",
    "Part III: The Destructive-Labor Camps — Ch.14: Changing One's Fate!",
    "Part III: The Destructive-Labor Camps — Ch.15: Punitive Measures and Devices",
    "Part III: The Destructive-Labor Camps — Ch.16: The Socially Friendly",
    "Part III: The Destructive-Labor Camps — Ch.17: Kids Making the Rounds",
    "Part III: The Destructive-Labor Camps — Ch.18: The Muses in Gulag",
    "Part III: The Destructive-Labor Camps — Ch.19: The Zeks as a Nation",
    "Part III: The Destructive-Labor Camps — Ch.20: The Dogs' Service",
    "Part III: The Destructive-Labor Camps — Ch.21: The Chiefs",
    "Part III: The Destructive-Labor Camps — Ch.22: We Are Building",
    "Part IV: The Soul and Barbed Wire — Ch.1: The Ascent",
    "Part IV: The Soul and Barbed Wire — Ch.2: Or Corruption?",
    "Part IV: The Soul and Barbed Wire — Ch.3: Our Muzzled Freedom",
    "Part IV: The Soul and Barbed Wire — Ch.4: Several Individual Stories",
    "Part V: Katorga — Ch.1: The Doomed",
    "Part V: Katorga — Ch.2: The First Katorga",
    "Part V: Katorga — Ch.3: Katorga's First Step",
    "Part VI: Exile — Ch.1: Exile in the First Years of Freedom",
    "Part VI: Exile — Ch.2: The Peasant Plague",
    "Part VI: Exile — Ch.3: Chains, Chains",
    "Part VI: Exile — Ch.4: Nations on Their Backs",
    "Part VI: Exile — Ch.5: End of Sentence, But Not Freedom",
    "Part VII: Stalin Is No More — Ch.1: The Wind of Freedom",
    "Part VII: Stalin Is No More — Ch.2: Tearing at the Bandage",
    "Part VII: Stalin Is No More — Ch.3: How Difficult It Is and Not at All Difficult",
    "Part VII: Stalin Is No More — Ch.4: And Again...",
  ],

  "crime and punishment": [
    "Part I — Ch.1: Raskolnikov Plans the Crime",
    "Part I — Ch.2: Marmeladov's Confession",
    "Part I — Ch.3: The Letter from Mother",
    "Part I — Ch.4: Raskolnikov Meets Sonya",
    "Part I — Ch.5: The Dream of the Mare",
    "Part I — Ch.6: The Murder",
    "Part I — Ch.7: The Aftermath",
    "Part II — Ch.1: Fever and Paranoia",
    "Part II — Ch.2: The Investigation Begins",
    "Part II — Ch.3: Razumikhin",
    "Part II — Ch.4: The Examining Magistrate",
    "Part II — Ch.5: Luzhin's Visit",
    "Part II — Ch.6: The Painter Nikolai",
    "Part II — Ch.7: Raskolnikov at the Crime Scene",
    "Part III — Ch.1: Razumikhin and the Dinner",
    "Part III — Ch.2: Porfiry's First Interview",
    "Part III — Ch.3: The Extraordinary Man Theory",
    "Part III — Ch.4: The Dream and the Ghost",
    "Part III — Ch.5: Svidrigailov Arrives",
    "Part III — Ch.6: Dunya and Luzhin",
    "Part IV — Ch.1: Luzhin Expelled",
    "Part IV — Ch.2: Raskolnikov and Sonya Read the Bible",
    "Part IV — Ch.3: Porfiry's Second Interview",
    "Part IV — Ch.4: Marmeladov's Funeral Feast",
    "Part IV — Ch.5: Katerina's Breakdown",
    "Part IV — Ch.6: Svidrigailov's Revelations",
    "Part V — Ch.1: Raskolnikov Tells Sonya",
    "Part V — Ch.2: Nikolai Confesses Falsely",
    "Part V — Ch.3: Porfiry's Final Interview",
    "Part V — Ch.4: The Confession Approaches",
    "Part V — Ch.5: Svidrigailov's Last Night",
    "Part VI — Ch.1: The Turning Point",
    "Part VI — Ch.2: Porfiry's Final Declaration",
    "Part VI — Ch.3: Raskolnikov's Farewell to His Mother",
    "Part VI — Ch.4: Svidrigailov's Death",
    "Part VI — Ch.5: The Confession",
    "Epilogue — Part 1: Prison in Siberia",
    "Epilogue — Part 2: Redemption and Renewal",
  ],

  "brothers karamazov": [
    "Part I, Book I: The History of a Family — Ch.1: Fyodor Pavlovich Karamazov",
    "Part I, Book I: The History of a Family — Ch.2: He Gets Rid of His Eldest Son",
    "Part I, Book I: The History of a Family — Ch.3: The Second Marriage and the Second Family",
    "Part I, Book I: The History of a Family — Ch.4: The Third Son Alyosha",
    "Part I, Book I: The History of a Family — Ch.5: Elders",
    "Part I, Book II: An Unfortunate Gathering — Ch.1: They Arrive at the Monastery",
    "Part I, Book II: An Unfortunate Gathering — Ch.2: The Old Buffoon",
    "Part I, Book II: An Unfortunate Gathering — Ch.3: Women of Faith",
    "Part I, Book II: An Unfortunate Gathering — Ch.4: A Lady of Little Faith",
    "Part I, Book II: An Unfortunate Gathering — Ch.5: So Be It! So Be It!",
    "Part I, Book II: An Unfortunate Gathering — Ch.6: Why Does Such a Man Live?",
    "Part I, Book II: An Unfortunate Gathering — Ch.7: A Seminarist-Careerist",
    "Part I, Book II: An Unfortunate Gathering — Ch.8: The Scandal",
    "Part I, Book III: The Sensualists — Ch.1: In the Servants' Quarters",
    "Part I, Book III: The Sensualists — Ch.2: Lizaveta Smerdyashchaya",
    "Part I, Book III: The Sensualists — Ch.3: The Confession of a Passionate Heart",
    "Part I, Book III: The Sensualists — Ch.4: The Confession Continued",
    "Part I, Book III: The Sensualists — Ch.5: The Confession Concluded",
    "Part I, Book III: The Sensualists — Ch.6: Smerdyakov",
    "Part I, Book III: The Sensualists — Ch.7: The Controversy",
    "Part I, Book III: The Sensualists — Ch.8: Over the Brandy",
    "Part I, Book III: The Sensualists — Ch.9: The Sensualists",
    "Part I, Book III: The Sensualists — Ch.10: Both Together",
    "Part I, Book III: The Sensualists — Ch.11: Another Reputation Ruined",
    "Part II, Book IV: Lacerations — Ch.1: Father Ferapont",
    "Part II, Book IV: Lacerations — Ch.2: At His Father's",
    "Part II, Book IV: Lacerations — Ch.3: A Meeting with the Schoolboys",
    "Part II, Book IV: Lacerations — Ch.4: At the Khokhlakov's",
    "Part II, Book IV: Lacerations — Ch.5: A Laceration in the Drawing Room",
    "Part II, Book IV: Lacerations — Ch.6: A Laceration in the Cottage",
    "Part II, Book IV: Lacerations — Ch.7: And in the Open Air",
    "Part II, Book V: Pro and Contra — Ch.1: The Engagement",
    "Part II, Book V: Pro and Contra — Ch.2: Smerdyakov with a Guitar",
    "Part II, Book V: Pro and Contra — Ch.3: The Brothers Make Friends",
    "Part II, Book V: Pro and Contra — Ch.4: Rebellion",
    "Part II, Book V: Pro and Contra — Ch.5: The Grand Inquisitor",
    "Part II, Book V: Pro and Contra — Ch.6: For a While a Very Obscure One",
    "Part II, Book V: Pro and Contra — Ch.7: 'It's Always Interesting to Talk with an Intelligent Man'",
    "Part II, Book VI: The Russian Monk — Ch.1: Elder Zosima and His Visitors",
    "Part II, Book VI: The Russian Monk — Ch.2: From the Life of the Elder Zosima",
    "Part II, Book VI: The Russian Monk — Ch.3: From the Discourses and Teachings of Elder Zosima",
    "Part III, Book VII: Alyosha — Ch.1: The Odour of Corruption",
    "Part III, Book VII: Alyosha — Ch.2: A Critical Moment",
    "Part III, Book VII: Alyosha — Ch.3: An Onion",
    "Part III, Book VII: Alyosha — Ch.4: Cana of Galilee",
    "Part III, Book VIII: Mitya — Ch.1: Kuzma Samsonov",
    "Part III, Book VIII: Mitya — Ch.2: Lyagavy",
    "Part III, Book VIII: Mitya — Ch.3: Gold Mines",
    "Part III, Book VIII: Mitya — Ch.4: In the Dark",
    "Part III, Book VIII: Mitya — Ch.5: A Sudden Resolution",
    "Part III, Book VIII: Mitya — Ch.6: Here I Come!",
    "Part III, Book VIII: Mitya — Ch.7: The First and Rightful One",
    "Part III, Book VIII: Mitya — Ch.8: Delirium",
    "Part III, Book IX: The Preliminary Investigation — Ch.1: The Start of Perhotin's Career",
    "Part III, Book IX: The Preliminary Investigation — Ch.2: The Alarm",
    "Part III, Book IX: The Preliminary Investigation — Ch.3: The Journey Through Hell",
    "Part III, Book IX: The Preliminary Investigation — Ch.4: The Second Ordeal",
    "Part III, Book IX: The Preliminary Investigation — Ch.5: The Third Ordeal",
    "Part III, Book IX: The Preliminary Investigation — Ch.6: The Public Prosecutor Catches Mitya",
    "Part III, Book IX: The Preliminary Investigation — Ch.7: Mitya's Great Secret",
    "Part III, Book IX: The Preliminary Investigation — Ch.8: The Evidence of the Witnesses",
    "Part III, Book IX: The Preliminary Investigation — Ch.9: Mitya Is Taken Away",
    "Part IV, Book X: The Boys — Ch.1: Kolya Krassotkin",
    "Part IV, Book X: The Boys — Ch.2: Kids",
    "Part IV, Book X: The Boys — Ch.3: The Schoolboy",
    "Part IV, Book X: The Boys — Ch.4: The Lost Dog",
    "Part IV, Book X: The Boys — Ch.5: By Ilyusha's Bedside",
    "Part IV, Book X: The Boys — Ch.6: Precocity",
    "Part IV, Book X: The Boys — Ch.7: Ilyusha",
    "Part IV, Book XI: Ivan — Ch.1: At Grushenka's",
    "Part IV, Book XI: Ivan — Ch.2: A Sick Little Foot",
    "Part IV, Book XI: Ivan — Ch.3: A Little Demon",
    "Part IV, Book XI: Ivan — Ch.4: A Hymn and a Secret",
    "Part IV, Book XI: Ivan — Ch.5: Not You, Not You!",
    "Part IV, Book XI: Ivan — Ch.6: The First Interview with Smerdyakov",
    "Part IV, Book XI: Ivan — Ch.7: The Second Visit to Smerdyakov",
    "Part IV, Book XI: Ivan — Ch.8: The Third and Last Interview with Smerdyakov",
    "Part IV, Book XI: Ivan — Ch.9: The Devil. Ivan's Nightmare",
    "Part IV, Book XI: Ivan — Ch.10: 'He Said That!'",
    "Part IV, Book XII: A Judicial Error — Ch.1: The Fatal Day",
    "Part IV, Book XII: A Judicial Error — Ch.2: Dangerous Witnesses",
    "Part IV, Book XII: A Judicial Error — Ch.3: The Medical Experts",
    "Part IV, Book XII: A Judicial Error — Ch.4: Fortune Smiles on Mitya",
    "Part IV, Book XII: A Judicial Error — Ch.5: A Sudden Catastrophe",
    "Part IV, Book XII: A Judicial Error — Ch.6: The Prosecutor's Speech",
    "Part IV, Book XII: A Judicial Error — Ch.7: A Historical Survey",
    "Part IV, Book XII: A Judicial Error — Ch.8: A Treatise on Smerdyakov",
    "Part IV, Book XII: A Judicial Error — Ch.9: The Psychology of the Prosecution",
    "Part IV, Book XII: A Judicial Error — Ch.10: The Speech for the Defence",
    "Part IV, Book XII: A Judicial Error — Ch.11: There Was No Money. There Was No Robbery",
    "Part IV, Book XII: A Judicial Error — Ch.12: And There Was No Murder Either",
    "Part IV, Book XII: A Judicial Error — Ch.13: The Sufferings of a Soul",
    "Part IV, Book XII: A Judicial Error — Ch.14: The Peasants Stand Firm",
    "Epilogue — Ch.1: Plans for Mitya's Escape",
    "Epilogue — Ch.2: Alyosha and Kolya",
    "Epilogue — Ch.3: Ilyusha's Funeral. The Speech at the Stone",
  ],

  "war and peace": [
    "Book I: 1805 — Part 1: Petersburg Society and the Coming War",
    "Book I: 1805 — Part 2: The Campaign in Austria",
    "Book I: 1805 — Part 3: The Battle of Austerlitz",
    "Book II: 1805–1807 — Part 1: After Austerlitz",
    "Book II: 1805–1807 — Part 2: Nikolai at War",
    "Book II: 1805–1807 — Part 3: Andrei's Retreat from Life",
    "Book II: 1805–1807 — Part 4: Natasha Grows Up",
    "Book II: 1805–1807 — Part 5: The Meeting of Andrei and Natasha",
    "Book III: 1812 — Part 1: The French Invasion Begins",
    "Book III: 1812 — Part 2: Borodino",
    "Book III: 1812 — Part 3: Moscow Burns",
    "Book IV: 1812–1813 — Part 1: The French in Moscow",
    "Book IV: 1812–1813 — Part 2: The Great Retreat",
    "Book IV: 1812–1813 — Part 3: The Death of Andrei",
    "Book IV: 1812–1813 — Part 4: Pierre's Captivity and Liberation",
    "Epilogue — Part 1: The Aftermath — 1820",
    "Epilogue — Part 2: Tolstoy's Philosophy of History",
  ],

  "anna karenina": [
    "Part I: Anna Arrives in Moscow",
    "Part II: The Affairs Begin",
    "Part III: Country Life and Levin's Work",
    "Part IV: The Crisis — Anna's Illness",
    "Part V: Levin and Kitty Marry",
    "Part VI: Anna and Vronsky in Italy",
    "Part VII: Anna's Jealousy and Despair",
    "Part VIII: Levin's Spiritual Crisis and Redemption",
  ],

  // ─────────────────────────────────────────────
  // DYSTOPIA & CLASSICS
  // ─────────────────────────────────────────────
  "1984": [
    "Part I — Ch.1: Winston's World",
    "Part I — Ch.2: Mrs. Parsons and the Children",
    "Part I — Ch.3: Dreams and the Past",
    "Part I — Ch.4: The Ministry of Truth",
    "Part I — Ch.5: Syme and Newspeak",
    "Part I — Ch.6: The Diary Entry",
    "Part I — Ch.7: The Proles",
    "Part I — Ch.8: The Shop in the Prole Quarter",
    "Part II — Ch.1: The Note",
    "Part II — Ch.2: The Meeting in the Country",
    "Part II — Ch.3: The Affair Begins",
    "Part II — Ch.4: The Rented Room",
    "Part II — Ch.5: Syme Disappears",
    "Part II — Ch.6: Charrington's Shop",
    "Part II — Ch.7: Talking in the Room Above the Shop",
    "Part II — Ch.8: O'Brien's Invitation",
    "Part II — Ch.9: The Book of Goldstein",
    "Part II — Ch.10: Arrest",
    "Part III — Ch.1: The Ministry of Love",
    "Part III — Ch.2: O'Brien's Real Face",
    "Part III — Ch.3: The Three Stages",
    "Part III — Ch.4: Reintegration",
    "Part III — Ch.5: Room 101",
    "Part III — Ch.6: The Chestnut Tree Café",
    "Appendix: The Principles of Newspeak",
  ],

  "animal farm": [
    "Chapter 1: Old Major's Speech",
    "Chapter 2: The Rebellion",
    "Chapter 3: The Harvest and the Seven Commandments",
    "Chapter 4: The Battle of the Cowshed",
    "Chapter 5: Snowball's Expulsion",
    "Chapter 6: Building the Windmill",
    "Chapter 7: Purges and Confessions",
    "Chapter 8: Napoleon Exalted",
    "Chapter 9: Boxer's Fate",
    "Chapter 10: The Pigs Walk Upright",
  ],

  "brave new world": [
    "Chapter 1: The Hatchery and Conditioning Centre",
    "Chapter 2: Neo-Pavlovian Conditioning",
    "Chapter 3: The World Controller and Bernard Marx",
    "Chapter 4: Bernard's Social Anxiety",
    "Chapter 5: Solidarity Service and Soma",
    "Chapter 6: The Director's Story and the Trip to the Reservation",
    "Chapter 7: The Savage Reservation",
    "Chapter 8: John's Story",
    "Chapter 9: The Soma Holiday",
    "Chapter 10: The Director Humiliated",
    "Chapter 11: The Savage in Civilisation",
    "Chapter 12: John Refuses to Perform",
    "Chapter 13: Lenina and John",
    "Chapter 14: Linda Dies",
    "Chapter 15: The Soma Riot",
    "Chapter 16: The World Controller Speaks",
    "Chapter 17: God and Religion Debated",
    "Chapter 18: John's Retreat and Death",
  ],

  "fahrenheit 451": [
    "Part I: The Hearth and the Salamander",
    "Part II: The Sieve and the Sand",
    "Part III: Burning Bright",
  ],

  "great gatsby": [
    "Chapter 1: Nick Arrives in West Egg",
    "Chapter 2: The Valley of Ashes and Tom's Affair",
    "Chapter 3: Gatsby's Party",
    "Chapter 4: Gatsby's Past and Wolfsheim",
    "Chapter 5: The Reunion of Jay and Daisy",
    "Chapter 6: Gatsby's True Origins",
    "Chapter 7: The Confrontation at the Plaza Hotel",
    "Chapter 8: Myrtle's Death and Gatsby Waits",
    "Chapter 9: Gatsby's Funeral and Nick's Departure",
  ],

  "to kill a mockingbird": [
    "Part I — Ch.1: Maycomb and the Finches",
    "Part I — Ch.2: Scout's First Day at School",
    "Part I — Ch.3: Walter Cunningham and Miss Caroline",
    "Part I — Ch.4: The Radley Place and Summer Games",
    "Part I — Ch.5: Miss Maudie and Boo Radley",
    "Part I — Ch.6: The Night Raid on the Radley Property",
    "Part I — Ch.7: The Gifts in the Tree",
    "Part I — Ch.8: Snow and Miss Maudie's Fire",
    "Part I — Ch.9: Scout Fights Cecil Jacobs; Christmas",
    "Part I — Ch.10: Atticus Shoots Tim Johnson",
    "Part I — Ch.11: Mrs. Dubose",
    "Part II — Ch.12: Calpurnia's Church",
    "Part II — Ch.13: Aunt Alexandra Arrives",
    "Part II — Ch.14: Dill Runs Away",
    "Part II — Ch.15: The Mob at the Jail",
    "Part II — Ch.16: The Trial Begins",
    "Part II — Ch.17: Heck Tate and Bob Ewell Testify",
    "Part II — Ch.18: Mayella Ewell Testifies",
    "Part II — Ch.19: Tom Robinson Testifies",
    "Part II — Ch.20: Atticus's Closing Argument",
    "Part II — Ch.21: The Verdict",
    "Part II — Ch.22: The Aftermath",
    "Part II — Ch.23: Talking About the Verdict",
    "Part II — Ch.24: The Missionary Tea Party",
    "Part II — Ch.25: Tom Robinson's Death",
    "Part II — Ch.26: Scout Reflects on Boo",
    "Part II — Ch.27: Bob Ewell's Threats",
    "Part II — Ch.28: The Attack on the Children",
    "Part II — Ch.29: The Discovery of Boo",
    "Part II — Ch.30: Heck Tate's Decision",
    "Part II — Ch.31: Scout Walks Boo Home",
  ],

  "of mice and men": [
    "Chapter 1: By the Salinas River — George and Lennie Arrive",
    "Chapter 2: The Ranch — Meeting the Workers",
    "Chapter 3: The Bunkhouse Evening — Slim and Carlson",
    "Chapter 4: Crooks's Room — The Outsiders",
    "Chapter 5: The Barn — Lennie's Mistake",
    "Chapter 6: The Riverbank — The End",
  ],

  "old man and the sea": [
    "Part 1: Santiago and Manolin — The Old Man and the Boy",
    "Part 2: Setting Out Alone — Day One on the Gulf Stream",
    "Part 3: The Great Fish Strikes — The Long Wait Begins",
    "Part 4: The Struggle — Pain, Endurance, and Brotherhood",
    "Part 5: The Kill — Santiago Harpoons the Marlin",
    "Part 6: The Return — Sharks Attack the Great Fish",
    "Part 7: The Harbor — The Skeleton and the Boy's Grief",
  ],

  "moby dick": [
    "Etymology and Extracts",
    "Ch.1: Loomings",
    "Ch.2: The Carpet-Bag",
    "Ch.3: The Spouter-Inn",
    "Ch.4: The Counterpane",
    "Ch.5: Breakfast",
    "Ch.6: The Street",
    "Ch.7: The Chapel",
    "Ch.8: The Pulpit",
    "Ch.9: The Sermon",
    "Ch.10: A Bosom Friend",
    "Ch.11: Nightgown",
    "Ch.12: Biographical",
    "Ch.13: Wheelbarrow",
    "Ch.14: Nantucket",
    "Ch.15: Chowder",
    "Ch.16: The Ship",
    "Ch.17: The Ramadan",
    "Ch.18: His Mark",
    "Ch.19: The Prophet",
    "Ch.20: All Astir",
    "Ch.21: Going Aboard",
    "Ch.22: Merry Christmas",
    "Ch.23: The Lee Shore",
    "Ch.24: The Advocate",
    "Ch.25: Postscript",
    "Ch.26: Knights and Squires",
    "Ch.27: Knights and Squires (continued)",
    "Ch.28: Ahab",
    "Ch.29: Enter Ahab",
    "Ch.30: The Pipe",
    "Ch.31: Queen Mab",
    "Ch.32: Cetology",
    "Ch.33: The Specksnyder",
    "Ch.34: The Cabin-Table",
    "Ch.35: The Mast-Head",
    "Ch.36: The Quarter-Deck",
    "Ch.37: Sunset",
    "Ch.38: Dusk",
    "Ch.39: First Night Watch",
    "Ch.40: Midnight, Forecastle",
    "Ch.41: Moby Dick",
    "Ch.42: The Whiteness of the Whale",
    "Ch.43: Hark!",
    "Ch.44: The Chart",
    "Ch.45: The Affidavit",
    "Ch.46: Surmises",
    "Ch.47: The Mat-Maker",
    "Ch.48: The First Lowering",
    "Ch.49: The Hyena",
    "Ch.50: Ahab's Boat and Crew",
    "Ch.51: The Spirit-Spout",
    "Ch.52: The Albatross",
    "Ch.53: The Gam",
    "Ch.54: The Town-Ho's Story",
    "Ch.55: Of the Monstrous Pictures of Whales",
    "Ch.56: Of the Less Erroneous Pictures of Whales",
    "Ch.57: Of Whales in Paint, in Teeth, in Wood",
    "Ch.58: Brit",
    "Ch.59: Squid",
    "Ch.60: The Line",
    "Ch.61: Stubb Kills a Whale",
    "Ch.62: The Dart",
    "Ch.63: The Crotch",
    "Ch.64: Stubb's Supper",
    "Ch.65: The Whale as a Dish",
    "Ch.66: The Shark Massacre",
    "Ch.67: Cutting In",
    "Ch.68: The Blanket",
    "Ch.69: The Funeral",
    "Ch.70: The Sphynx",
    "Ch.71: The Jeroboam's Story",
    "Ch.72: The Monkey-Rope",
    "Ch.73: Stubb and Flask Kill a Right Whale",
    "Ch.74: The Sperm Whale's Head",
    "Ch.75: The Right Whale's Head",
    "Ch.76: The Battering-Ram",
    "Ch.77: The Great Heidelburgh Tun",
    "Ch.78: Cistern and Buckets",
    "Ch.79: The Prairie",
    "Ch.80: The Nut",
    "Ch.81: The Pequod Meets the Virgin",
    "Ch.82: The Honour and Glory of Whaling",
    "Ch.83: Jonah Historically Regarded",
    "Ch.84: Pitchpoling",
    "Ch.85: The Fountain",
    "Ch.86: The Tail",
    "Ch.87: The Grand Armada",
    "Ch.88: Schools and Schoolmasters",
    "Ch.89: Fast-Fish and Loose-Fish",
    "Ch.90: Heads or Tails",
    "Ch.91: The Pequod Meets the Rose-Bud",
    "Ch.92: Ambergris",
    "Ch.93: The Castaway",
    "Ch.94: A Squeeze of the Hand",
    "Ch.95: The Cassock",
    "Ch.96: The Try-Works",
    "Ch.97: The Lamp",
    "Ch.98: Stowing Down and Clearing Up",
    "Ch.99: The Doubloon",
    "Ch.100: Leg and Arm",
    "Ch.101: The Decanter",
    "Ch.102: A Bower in the Arsacides",
    "Ch.103: Measurement of the Whale's Skeleton",
    "Ch.104: The Fossil Whale",
    "Ch.105: Does the Whale Diminish?",
    "Ch.106: Ahab's Leg",
    "Ch.107: The Carpenter",
    "Ch.108: Ahab and the Carpenter",
    "Ch.109: Ahab and Starbuck in the Cabin",
    "Ch.110: Queequeg in His Coffin",
    "Ch.111: The Pacific",
    "Ch.112: The Blacksmith",
    "Ch.113: The Forge",
    "Ch.114: The Gilder",
    "Ch.115: The Pequod Meets the Bachelor",
    "Ch.116: The Dying Whale",
    "Ch.117: The Whale Watch",
    "Ch.118: The Quadrant",
    "Ch.119: The Candles",
    "Ch.120: The Deck Towards the End of the First Night Watch",
    "Ch.121: Midnight — The Forecastle Bulwarks",
    "Ch.122: Midnight Aloft — Thunder and Lightning",
    "Ch.123: The Musket",
    "Ch.124: The Needle",
    "Ch.125: The Log and Line",
    "Ch.126: The Life-Buoy",
    "Ch.127: The Deck",
    "Ch.128: The Pequod Meets the Rachel",
    "Ch.129: The Cabin",
    "Ch.130: The Hat",
    "Ch.131: The Pequod Meets the Delight",
    "Ch.132: The Symphony",
    "Ch.133: The Chase — First Day",
    "Ch.134: The Chase — Second Day",
    "Ch.135: The Chase — Third Day",
    "Epilogue",
  ],

  "don quixote": [
    "Part I, Ch.1: The Character of the Knight",
    "Part I, Ch.2: The First Sallying Forth",
    "Part I, Ch.3: The Knighting Ceremony",
    "Part I, Ch.4: The Merchants of Toledo",
    "Part I, Ch.5: The Curate and the Barber",
    "Part I, Ch.6: The Burning of the Library",
    "Part I, Ch.7: Sancho Panza Joins as Squire",
    "Part I, Ch.8: The Adventure of the Windmills",
    "Part I, Ch.9: The Battle with the Basque",
    "Part I, Ch.10: The Manchegan Shepherdess Marcela",
    "Part I, Ch.11: The Inn as Castle",
    "Part I, Ch.12: The Adventure with the Penitents",
    "Part I, Ch.13: The Galeotes (Galley Slaves)",
    "Part I, Ch.14: Sierra Morena — Penance for Dulcinea",
    "Part I, Ch.15: Cardenio and Luscinda",
    "Part I, Ch.16: The Return of Don Quixote",
    "Part II, Ch.1: Don Quixote and the Knight of the Mirrors",
    "Part II, Ch.2: Sancho Panza Governor of Barataria",
    "Part II, Ch.3: The Cave of Montesinos",
    "Part II, Ch.4: The Enchantment of Dulcinea",
    "Part II, Ch.5: The Ducal Palace",
    "Part II, Ch.6: Adventures at the Duke's Court",
    "Part II, Ch.7: The Island of Barataria — Sancho Governs",
    "Part II, Ch.8: Altisidora and Her Feigned Love",
    "Part II, Ch.9: The Knight of the White Moon",
    "Part II, Ch.10: The Defeat and the Return Home",
    "Part II, Ch.11: The Death of Don Quixote",
  ],

  // ─────────────────────────────────────────────
  // ANCIENT EPICS & PLAYS
  // ─────────────────────────────────────────────
  odyssey: [
    "Book I: Athena Appeals to Zeus for Odysseus",
    "Book II: Telemachus Calls an Assembly",
    "Book III: Telemachus Visits Nestor at Pylos",
    "Book IV: Telemachus Visits Menelaus at Sparta",
    "Book V: Calypso Releases Odysseus",
    "Book VI: Odysseus and the Phaeacians — Nausicaä",
    "Book VII: The Palace of Alcinous",
    "Book VIII: Games and the Song of Demodocus",
    "Book IX: The Cyclops — Polyphemus",
    "Book X: Circe's Island",
    "Book XI: The Land of the Dead — The Nekyia",
    "Book XII: Scylla and Charybdis; the Cattle of the Sun",
    "Book XIII: Return to Ithaca",
    "Book XIV: Odysseus and the Swineherd Eumaeus",
    "Book XV: Telemachus Returns to Ithaca",
    "Book XVI: Father and Son Reunited",
    "Book XVII: Odysseus Returns to the Palace as a Beggar",
    "Book XVIII: The Beggar Irus",
    "Book XIX: Penelope and the Disguised Odysseus",
    "Book XX: The Eve of Reckoning",
    "Book XXI: The Trial of the Bow",
    "Book XXII: The Slaughter of the Suitors",
    "Book XXIII: Penelope Recognises Odysseus",
    "Book XXIV: Peace in Ithaca",
  ],

  iliad: [
    "Book I: The Rage of Achilles and the Plague",
    "Book II: The Dream of Agamemnon and the Catalogue of Ships",
    "Book III: The Duel of Paris and Menelaus",
    "Book IV: The Truce Broken — Battle Begins",
    "Book V: The Aristeia of Diomedes",
    "Book VI: Hector and Andromache",
    "Book VII: Hector Duels Ajax",
    "Book VIII: Zeus Turns the Battle",
    "Book IX: The Embassy to Achilles",
    "Book X: The Doloneia — Night Raid",
    "Book XI: Agamemnon's Aristeia — The Wounding of Heroes",
    "Book XII: The Battle at the Wall",
    "Book XIII: Poseidon Aids the Greeks",
    "Book XIV: The Deception of Zeus",
    "Book XV: Zeus Reasserts Control",
    "Book XVI: Patroclus Fights and Falls",
    "Book XVII: The Battle Over Patroclus's Body",
    "Book XVIII: The Shield of Achilles",
    "Book XIX: The Reconciliation of Achilles and Agamemnon",
    "Book XX: The Gods Enter Battle",
    "Book XXI: The Battle at the River Scamander",
    "Book XXII: The Death of Hector",
    "Book XXIII: The Funeral Games for Patroclus",
    "Book XXIV: Priam Ransoms Hector's Body",
  ],

  hamlet: [
    "Act I, Scene 1: The Ghost on the Battlements",
    "Act I, Scene 2: The Court — Hamlet's First Soliloquy",
    "Act I, Scene 3: Polonius's Advice to Laertes",
    "Act I, Scene 4: Hamlet Meets the Ghost",
    "Act I, Scene 5: The Ghost Reveals the Murder",
    "Act II, Scene 1: Ophelia Reports Hamlet's Madness",
    "Act II, Scene 2: The Players Arrive — 'What a Piece of Work Is Man'",
    "Act III, Scene 1: 'To Be or Not to Be'",
    "Act III, Scene 2: The Play Within the Play",
    "Act III, Scene 3: Claudius Prays — Hamlet Hesitates",
    "Act III, Scene 4: The Closet Scene — Polonius Killed",
    "Act IV, Scene 1: Gertrude Tells Claudius",
    "Act IV, Scene 2: Hamlet Hides the Body",
    "Act IV, Scene 3: Hamlet Sent to England",
    "Act IV, Scene 4: Fortinbras — Hamlet's Soliloquy on Action",
    "Act IV, Scene 5: Ophelia's Madness",
    "Act IV, Scene 6: Hamlet's Letter to Horatio",
    "Act IV, Scene 7: Claudius and Laertes Plot",
    "Act V, Scene 1: The Gravediggers — Yorick's Skull",
    "Act V, Scene 2: The Duel and the Deaths",
  ],

  // ─────────────────────────────────────────────
  // PHILOSOPHY & ANCIENT THOUGHT
  // ─────────────────────────────────────────────
  meditations: [
    "Book I: Debts and Lessons — Gratitude to Teachers",
    "Book II: On the Frailty of Life and the Present Moment",
    "Book III: On the Goods of the Mind",
    "Book IV: On Impermanence and the Whole",
    "Book V: On Duty and Waking with Purpose",
    "Book VI: On Opinion, Nature, and Reason",
    "Book VII: On Mastery of Oneself",
    "Book VIII: On the Rational Soul",
    "Book IX: On Anger, Opinion, and the Common Good",
    "Book X: On Cheerfulness and Purpose",
    "Book XI: On the Mind's Independence",
    "Book XII: On Living the Final Days Well",
  ],

  republic: [
    "Book I: Socrates Questions the Definition of Justice",
    "Book II: Glaucon's Challenge — The Ring of Gyges",
    "Book III: Education of the Guardians — Music and Gymnastics",
    "Book IV: The Four Virtues of the Ideal State",
    "Book V: The Community of Women and Children",
    "Book VI: The Philosopher-King and the Sun Analogy",
    "Book VII: The Allegory of the Cave",
    "Book VIII: The Decline of the State — Democracy and Tyranny",
    "Book IX: The Tyrannical Soul and True Happiness",
    "Book X: The Myth of Er and the Immortality of the Soul",
  ],

  "nicomachean ethics": [
    "Book I: Happiness as the Highest Good",
    "Book II: Moral Virtue and the Doctrine of the Mean",
    "Book III: Voluntary Action, Choice, and Courage",
    "Book IV: The Virtues — Liberality, Magnificence, Pride",
    "Book V: Justice — Its Kinds and Conditions",
    "Book VI: Intellectual Virtues — Practical Wisdom (Phronesis)",
    "Book VII: Weakness of Will (Akrasia) and Pleasure",
    "Book VIII: Friendship — Its Nature and Kinds",
    "Book IX: Friendship Concluded — Self-Love and the Good Man",
    "Book X: Pleasure and the Contemplative Life",
  ],

  "thus spoke zarathustra": [
    "Prologue: Zarathustra Descends from the Mountain",
    "Part I: The Three Metamorphoses",
    "Part I: The Academic Chairs of Virtue",
    "Part I: The Afterworldly",
    "Part I: The Despisers of the Body",
    "Part I: Joys and Passions",
    "Part I: The Pale Criminal",
    "Part I: On Reading and Writing",
    "Part I: The Tree on the Mountainside",
    "Part I: The Preachers of Death",
    "Part I: The New Idol (The State)",
    "Part I: The Flies of the Market Place",
    "Part I: Chastity and the Friend",
    "Part I: The Thousand and One Goals",
    "Part I: Neighbour-Love",
    "Part I: The Way of the Creator",
    "Part I: Old and Young Women",
    "Part I: The Adder's Bite",
    "Part I: Child and Marriage",
    "Part I: Voluntary Death",
    "Part I: The Gift-Giving Virtue",
    "Part II: The Child with the Mirror",
    "Part II: Upon the Blessed Isles",
    "Part II: The Pitying",
    "Part II: The Priests",
    "Part II: The Virtuous",
    "Part II: The Rabble",
    "Part II: The Tarantulas",
    "Part II: The Famous Wise Men",
    "Part II: The Night Song",
    "Part II: The Dancing Song",
    "Part II: The Grave Song",
    "Part II: Self-Overcoming",
    "Part II: The Sublime Ones",
    "Part II: The Land of Culture",
    "Part II: Immaculate Perception",
    "Part II: Scholars",
    "Part II: Poets",
    "Part II: Great Events",
    "Part II: The Soothsayer",
    "Part II: On Redemption",
    "Part II: Manly Prudence",
    "Part II: The Stillest Hour",
    "Part III: The Wanderer",
    "Part III: The Vision and the Enigma",
    "Part III: Of Involuntary Bliss",
    "Part III: Before Sunrise",
    "Part III: The Belittling Virtue",
    "Part III: On the Olive Mount",
    "Part III: On Passing By",
    "Part III: The Apostates",
    "Part III: The Return Home",
    "Part III: The Three Evils",
    "Part III: On the Spirit of Gravity",
    "Part III: Old and New Tables",
    "Part III: The Convalescent",
    "Part III: Of the Great Longing",
    "Part III: The Second Dancing Song",
    "Part III: The Seven Seals",
    "Part IV: The Honey Sacrifice",
    "Part IV: The Cry of Distress",
    "Part IV: Conversation with the Kings",
    "Part IV: The Leech",
    "Part IV: The Magician",
    "Part IV: Out of Service",
    "Part IV: The Ugliest Man",
    "Part IV: The Voluntary Beggar",
    "Part IV: The Shadow",
    "Part IV: At Noon",
    "Part IV: The Greeting",
    "Part IV: The Supper",
    "Part IV: The Higher Man",
    "Part IV: The Song of Melancholy",
    "Part IV: Science",
    "Part IV: Among Daughters of the Desert",
    "Part IV: The Awakening",
    "Part IV: The Ass Festival",
    "Part IV: The Drunken Song",
    "Part IV: The Sign",
  ],

  "beyond good and evil": [
    "Preface",
    "Part I: On the Prejudices of Philosophers",
    "Part II: The Free Spirit",
    "Part III: The Religious Nature",
    "Part IV: Epigrams and Interludes",
    "Part V: On the Natural History of Morals",
    "Part VI: We Scholars",
    "Part VII: Our Virtues",
    "Part VIII: Peoples and Fatherlands",
    "Part IX: What Is Noble?",
    "From High Mountains — Aftersong",
  ],

  prince: [
    "Ch.1: How Many Kinds of Principalities There Are",
    "Ch.2: Hereditary Principalities",
    "Ch.3: Mixed Principalities",
    "Ch.4: Why the Kingdom of Darius Did Not Rebel",
    "Ch.5: How to Govern Cities Previously Free",
    "Ch.6: New Principalities Acquired by Prowess",
    "Ch.7: New Principalities Acquired by Fortune",
    "Ch.8: Principalities Acquired Through Wickedness",
    "Ch.9: The Civil Principality",
    "Ch.10: How to Measure Every Principality",
    "Ch.11: Ecclesiastical Principalities",
    "Ch.12: Different Kinds of Troops",
    "Ch.13: Auxiliary, Mixed, and Native Troops",
    "Ch.14: A Prince's Duty on Military Matters",
    "Ch.15: Things That Earn Men Praise or Blame",
    "Ch.16: Liberality and Parsimony",
    "Ch.17: Cruelty and Compassion",
    "Ch.18: How Princes Should Keep Faith",
    "Ch.19: Avoiding Contempt and Hatred",
    "Ch.20: Whether Fortresses Are Useful",
    "Ch.21: How a Prince Should Act to Gain Renown",
    "Ch.22: A Prince's Ministers",
    "Ch.23: How to Avoid Flatterers",
    "Ch.24: Why Italian Princes Have Lost Their States",
    "Ch.25: Fortune's Role in Human Affairs",
    "Ch.26: An Exhortation to Liberate Italy",
  ],

  // ─────────────────────────────────────────────
  // PSYCHOLOGY & COGNITIVE SCIENCE
  // ─────────────────────────────────────────────
  "the power of habit": [
    "Prologue: The Habit Cue-Routine-Reward Loop",
    "Part I — Ch.1: The Habit Loop — How Habits Work",
    "Part I — Ch.2: The Craving Brain — How to Create New Habits",
    "Part I — Ch.3: The Golden Rule of Habit Change",
    "Part II — Ch.4: Keystone Habits — Which Habits Matter Most",
    "Part II — Ch.5: Starbucks and the Habit of Success",
    "Part II — Ch.6: The Power of a Crisis",
    "Part II — Ch.7: How Target Knows What You Want Before You Do",
    "Part III — Ch.8: Saddleback Church and the Montgomery Bus Boycott",
    "Part III — Ch.9: The Neurology of Free Will",
    "Appendix: A Reader's Guide to Using These Ideas",
  ],

  "thinking fast and slow": [
    "Part I, Introduction: The Two Systems",
    "Part I, Ch.1: The Characters of the Story",
    "Part I, Ch.2: Attention and Effort",
    "Part I, Ch.3: The Lazy Controller",
    "Part I, Ch.4: The Associative Machine",
    "Part I, Ch.5: Cognitive Ease",
    "Part I, Ch.6: Norms, Surprises, and Causes",
    "Part I, Ch.7: A Machine for Jumping to Conclusions",
    "Part I, Ch.8: How Judgments Happen",
    "Part I, Ch.9: Answering an Easier Question",
    "Part II, Ch.10: The Law of Small Numbers",
    "Part II, Ch.11: Anchors",
    "Part II, Ch.12: The Science of Availability",
    "Part II, Ch.13: Availability, Emotion, and Risk",
    "Part II, Ch.14: Tom W's Specialty",
    "Part II, Ch.15: Linda: Less Is More",
    "Part II, Ch.16: Causes Trump Statistics",
    "Part II, Ch.17: Regression to the Mean",
    "Part II, Ch.18: Taming Intuitive Predictions",
    "Part III, Ch.19: The Illusion of Understanding",
    "Part III, Ch.20: The Illusion of Validity",
    "Part III, Ch.21: Intuitions vs. Formulas",
    "Part III, Ch.22: Expert Intuition: When Can We Trust It?",
    "Part III, Ch.23: The Outside View",
    "Part III, Ch.24: The Engine of Capitalism",
    "Part IV, Ch.25: Bernoulli's Errors",
    "Part IV, Ch.26: Prospect Theory",
    "Part IV, Ch.27: The Endowment Effect",
    "Part IV, Ch.28: Bad Events",
    "Part IV, Ch.29: The Fourfold Pattern",
    "Part IV, Ch.30: Rare Events",
    "Part IV, Ch.31: Risk Policies",
    "Part IV, Ch.32: Keeping Score",
    "Part IV, Ch.33: Reversals",
    "Part IV, Ch.34: Frames and Reality",
    "Part V, Ch.35: Two Selves",
    "Part V, Ch.36: Life as a Story",
    "Part V, Ch.37: Experienced Well-Being",
    "Part V, Ch.38: Thinking About Life",
    "Conclusions",
  ],

  "mans search for meaning": [
    "Preface to the 1992 Edition",
    "Part I: Experiences in a Concentration Camp",
    "Part I: Phase One — Arrival and Initial Shock",
    "Part I: Phase Two — Life in the Camp",
    "Part I: Phase Three — After Liberation",
    "Part II: Logotherapy in a Nutshell",
    "Part II: The Will to Meaning",
    "Part II: The Existential Vacuum",
    "Part II: The Meaning of Life",
    "Part II: The Essence of Existence",
    "Part II: The Meaning of Love",
    "Part II: The Meaning of Suffering",
    "Part II: The Super-Meaning",
    "Part II: The Meaning of Life Is Unique",
    "Part II: Logotherapy as a Technique",
    "Part II: The Collective Neurosis",
    "Postscript: The Case for a Tragic Optimism",
  ],

  "power of now": [
    "Preface",
    "Ch.1: You Are Not Your Mind",
    "Ch.2: Consciousness — The Way Out of Pain",
    "Ch.3: Moving Deeply into the Now",
    "Ch.4: Mind Strategies for Avoiding the Now",
    "Ch.5: The State of Presence",
    "Ch.6: The Inner Body",
    "Ch.7: Portals into the Unmanifested",
    "Ch.8: Enlightened Relationships",
    "Ch.9: Beyond Happiness and Unhappiness",
    "Ch.10: The Meaning of Surrender",
  ],

  // ─────────────────────────────────────────────
  // HISTORY & ANTHROPOLOGY
  // ─────────────────────────────────────────────
  sapiens: [
    "Part I: The Cognitive Revolution — Ch.1: An Animal of No Significance",
    "Part I: The Cognitive Revolution — Ch.2: The Tree of Knowledge",
    "Part I: The Cognitive Revolution — Ch.3: A Day in the Life of Adam and Eve",
    "Part I: The Cognitive Revolution — Ch.4: The Flood",
    "Part II: The Agricultural Revolution — Ch.5: History's Biggest Fraud",
    "Part II: The Agricultural Revolution — Ch.6: Building Pyramids",
    "Part II: The Agricultural Revolution — Ch.7: Memory Overload",
    "Part II: The Agricultural Revolution — Ch.8: There Is No Justice in History",
    "Part III: The Unification of Humankind — Ch.9: The Arrow of History",
    "Part III: The Unification of Humankind — Ch.10: The Smell of Money",
    "Part III: The Unification of Humankind — Ch.11: Imperial Visions",
    "Part III: The Unification of Humankind — Ch.12: The Law of Religion",
    "Part III: The Unification of Humankind — Ch.13: The Secret of Success",
    "Part IV: The Scientific Revolution — Ch.14: The Discovery of Ignorance",
    "Part IV: The Scientific Revolution — Ch.15: The Marriage of Science and Empire",
    "Part IV: The Scientific Revolution — Ch.16: The Capitalist Creed",
    "Part IV: The Scientific Revolution — Ch.17: The Wheels of Industry",
    "Part IV: The Scientific Revolution — Ch.18: A Permanent Revolution",
    "Part IV: The Scientific Revolution — Ch.19: And They Lived Happily Ever After",
    "Part IV: The Scientific Revolution — Ch.20: The End of Homo Sapiens",
    "Afterword: The Animal That Became a God",
  ],

  "homo deus": [
    "Part I: Homo Sapiens Conquers the World — Ch.1: The New Human Agenda",
    "Part I: Homo Sapiens Conquers the World — Ch.2: The Anthropocene",
    "Part I: Homo Sapiens Conquers the World — Ch.3: The Human Spark",
    "Part II: Homo Sapiens Gives Meaning to the World — Ch.4: The Storytellers",
    "Part II: Homo Sapiens Gives Meaning to the World — Ch.5: The Odd Couple",
    "Part II: Homo Sapiens Gives Meaning to the World — Ch.6: The Modern Covenant",
    "Part II: Homo Sapiens Gives Meaning to the World — Ch.7: The Humanist Revolution",
    "Part III: Homo Sapiens Loses Control — Ch.8: The Time Bomb in the Laboratory",
    "Part III: Homo Sapiens Loses Control — Ch.9: The Great Decoupling",
    "Part III: Homo Sapiens Loses Control — Ch.10: The Ocean of Consciousness",
    "Part III: Homo Sapiens Loses Control — Ch.11: The Data Religion",
  ],

  // ─────────────────────────────────────────────
  // BIOLOGY & SCIENCE
  // ─────────────────────────────────────────────
  "selfish gene": [
    "Ch.1: Why Are People?",
    "Ch.2: The Replicators",
    "Ch.3: Immortal Coils",
    "Ch.4: The Gene Machine",
    "Ch.5: Aggression: Stability and the Selfish Machine",
    "Ch.6: Genesmanship",
    "Ch.7: Family Planning",
    "Ch.8: Battle of the Generations",
    "Ch.9: Battle of the Sexes",
    "Ch.10: You Scratch My Back, I'll Ride on Yours",
    "Ch.11: Memes: The New Replicators",
    "Ch.12: Nice Guys Finish First",
    "Ch.13: The Long Reach of the Gene",
  ],

  "brief history of time": [
    "Ch.1: Our Picture of the Universe",
    "Ch.2: Space and Time",
    "Ch.3: The Expanding Universe",
    "Ch.4: The Uncertainty Principle",
    "Ch.5: Elementary Particles and the Forces of Nature",
    "Ch.6: Black Holes",
    "Ch.7: Black Holes Ain't So Black",
    "Ch.8: The Origin and Fate of the Universe",
    "Ch.9: The Arrow of Time",
    "Ch.10: Wormholes and Time Travel",
    "Ch.11: The Unification of Physics",
    "Ch.12: Conclusion",
  ],

  "structure of scientific revolutions": [
    "Preface",
    "Ch.1: Introduction — A Role for History",
    "Ch.2: The Route to Normal Science",
    "Ch.3: The Nature of Normal Science",
    "Ch.4: Normal Science as Puzzle-Solving",
    "Ch.5: The Priority of Paradigms",
    "Ch.6: Anomaly and the Emergence of Scientific Discoveries",
    "Ch.7: Crisis and the Emergence of Scientific Theories",
    "Ch.8: The Response to Crisis",
    "Ch.9: The Nature and Necessity of Scientific Revolutions",
    "Ch.10: Revolutions as Changes of World View",
    "Ch.11: The Invisibility of Revolutions",
    "Ch.12: The Resolution of Revolutions",
    "Ch.13: Progress Through Revolutions",
    "Postscript: 1969",
  ],

  "origin of species": [
    "Introduction",
    "Ch.1: Variation Under Domestication",
    "Ch.2: Variation Under Nature",
    "Ch.3: Struggle for Existence",
    "Ch.4: Natural Selection",
    "Ch.5: Laws of Variation",
    "Ch.6: Difficulties on Theory",
    "Ch.7: Instinct",
    "Ch.8: Hybridism",
    "Ch.9: On the Imperfection of the Geological Record",
    "Ch.10: On the Geological Succession of Organic Beings",
    "Ch.11: Geographical Distribution",
    "Ch.12: Geographical Distribution (continued)",
    "Ch.13: Mutual Affinities of Organic Beings",
    "Ch.14: Recapitulation and Conclusion",
  ],

  // ─────────────────────────────────────────────
  // STRATEGY & POWER
  // ─────────────────────────────────────────────
  "art of war": [
    "Ch.1: Laying Plans",
    "Ch.2: Waging War",
    "Ch.3: Attack by Stratagem",
    "Ch.4: Tactical Dispositions",
    "Ch.5: Energy",
    "Ch.6: Weak Points and Strong",
    "Ch.7: Maneuvering",
    "Ch.8: Variation in Tactics",
    "Ch.9: The Army on the March",
    "Ch.10: Terrain",
    "Ch.11: The Nine Situations",
    "Ch.12: The Attack by Fire",
    "Ch.13: The Use of Spies",
  ],

  "48 laws of power": [
    "Introduction",
    "Law 1: Never Outshine the Master",
    "Law 2: Never Put Too Much Trust in Friends",
    "Law 3: Conceal Your Intentions",
    "Law 4: Always Say Less Than Necessary",
    "Law 5: So Much Depends on Reputation",
    "Law 6: Court Attention at All Costs",
    "Law 7: Get Others to Do the Work for You",
    "Law 8: Make Other People Come to You",
    "Law 9: Win Through Your Actions, Never Through Argument",
    "Law 10: Infection — Avoid the Unhappy and Unlucky",
    "Law 11: Make People Dependent on You",
    "Law 12: Use Selective Honesty to Disarm",
    "Law 13: Appeal to Self-Interest",
    "Law 14: Pose as a Friend, Work as a Spy",
    "Law 15: Crush Your Enemy Totally",
    "Law 16: Use Absence to Increase Respect",
    "Law 17: Keep Others in Suspended Terror",
    "Law 18: Do Not Build Fortresses",
    "Law 19: Know Who You're Dealing With",
    "Law 20: Do Not Commit to Anyone",
    "Law 21: Play a Sucker to Catch a Sucker",
    "Law 22: Use the Surrender Tactic",
    "Law 23: Concentrate Your Forces",
    "Law 24: Play the Perfect Courtier",
    "Law 25: Re-Create Yourself",
    "Law 26: Keep Your Hands Clean",
    "Law 27: Play on People's Need to Believe",
    "Law 28: Enter Action with Boldness",
    "Law 29: Plan All the Way to the End",
    "Law 30: Make Your Accomplishments Seem Effortless",
    "Law 31: Control the Options",
    "Law 32: Play to People's Fantasies",
    "Law 33: Discover Each Man's Thumbscrew",
    "Law 34: Be Royal in Your Own Fashion",
    "Law 35: Master the Art of Timing",
    "Law 36: Disdain Things You Cannot Have",
    "Law 37: Create Compelling Spectacles",
    "Law 38: Think as You Like but Behave Like Others",
    "Law 39: Stir Up Waters to Catch Fish",
    "Law 40: Despise the Free Lunch",
    "Law 41: Avoid Stepping into a Great Man's Shoes",
    "Law 42: Strike the Shepherd and the Sheep Will Scatter",
    "Law 43: Work on the Hearts and Minds of Others",
    "Law 44: Disarm and Infuriate with the Mirror Effect",
    "Law 45: Preach the Need for Change, Never Reform Too Much",
    "Law 46: Never Appear Too Perfect",
    "Law 47: Do Not Go Past the Mark You Aimed For",
    "Law 48: Assume Formlessness",
  ],

  "33 strategies of war": [
    "Preface: The Declares War on Himself",
    "Part I: Self-Directed Warfare — Strategy 1: Declare War on Your Enemies",
    "Part I: Self-Directed Warfare — Strategy 2: Do Not Fight the Last War",
    "Part I: Self-Directed Warfare — Strategy 3: Amidst the Turmoil of Events",
    "Part I: Self-Directed Warfare — Strategy 4: Create a Sense of Urgency",
    "Part II: Organizational Warfare — Strategy 5: Avoid the Snares of Groupthink",
    "Part II: Organizational Warfare — Strategy 6: Segment Your Forces",
    "Part II: Organizational Warfare — Strategy 7: Transform Your War Into a Crusade",
    "Part III: Defensive Warfare — Strategy 8: Pick Your Battles Carefully",
    "Part III: Defensive Warfare — Strategy 9: Turn the Tables",
    "Part III: Defensive Warfare — Strategy 10: Create a Threatening Presence",
    "Part III: Defensive Warfare — Strategy 11: Trade Space for Time",
    "Part IV: Offensive Warfare — Strategy 12: Lose Battles but Win the War",
    "Part IV: Offensive Warfare — Strategy 13: Know Your Enemy",
    "Part IV: Offensive Warfare — Strategy 14: Overwhelm Resistance with Speed",
    "Part IV: Offensive Warfare — Strategy 15: Control the Dynamic",
    "Part IV: Offensive Warfare — Strategy 16: Hit Them Where It Hurts",
    "Part IV: Offensive Warfare — Strategy 17: Defeat Them in Detail",
    "Part IV: Offensive Warfare — Strategy 18: Expose and Attack Your Enemy's Soft Flank",
    "Part IV: Offensive Warfare — Strategy 19: Envelop the Enemy",
    "Part IV: Offensive Warfare — Strategy 20: Maneuver Them Into Weakness",
    "Part IV: Offensive Warfare — Strategy 21: Negotiate While Advancing",
    "Part IV: Offensive Warfare — Strategy 22: Know How to End Things",
    "Part V: Unconventional (Dirty) Warfare — Strategy 23: Weave a Seamless Blend of Fact and Fiction",
    "Part V: Unconventional (Dirty) Warfare — Strategy 24: Take the Line of Least Expectation",
    "Part V: Unconventional (Dirty) Warfare — Strategy 25: Occupy the Moral High Ground",
    "Part V: Unconventional (Dirty) Warfare — Strategy 26: Deny Them Targets",
    "Part V: Unconventional (Dirty) Warfare — Strategy 27: Seem to Work for the Interests of Others",
    "Part V: Unconventional (Dirty) Warfare — Strategy 28: Give Your Rivals Enough Rope to Hang Themselves",
    "Part V: Unconventional (Dirty) Warfare — Strategy 29: Take Small Bites",
    "Part V: Unconventional (Dirty) Warfare — Strategy 30: Penetrate Their Minds",
    "Part V: Unconventional (Dirty) Warfare — Strategy 31: Destroy From Within",
    "Part V: Unconventional (Dirty) Warfare — Strategy 32: Dominate While Seeming to Submit",
    "Part V: Unconventional (Dirty) Warfare — Strategy 33: Sow Uncertainty and Panic",
  ],

  // ─────────────────────────────────────────────
  // SELF-HELP CLASSICS
  // ─────────────────────────────────────────────
  "how to win friends and influence people": [
    "Part I: Fundamental Techniques in Handling People — Ch.1: If You Want to Gather Honey",
    "Part I: Fundamental Techniques in Handling People — Ch.2: The Big Secret of Dealing with People",
    "Part I: Fundamental Techniques in Handling People — Ch.3: He Who Can Do This Has the Whole World",
    "Part II: Six Ways to Make People Like You — Ch.1: Do This and You'll Be Welcome Anywhere",
    "Part II: Six Ways to Make People Like You — Ch.2: A Simple Way to Make a Good First Impression",
    "Part II: Six Ways to Make People Like You — Ch.3: If You Don't Do This, You Are Headed for Trouble",
    "Part II: Six Ways to Make People Like You — Ch.4: An Easy Way to Become a Good Conversationalist",
    "Part II: Six Ways to Make People Like You — Ch.5: How to Interest People",
    "Part II: Six Ways to Make People Like You — Ch.6: How to Make People Like You Instantly",
    "Part III: How to Win People to Your Way of Thinking — Ch.1: You Can't Win an Argument",
    "Part III: How to Win People to Your Way of Thinking — Ch.2: A Sure Way of Making Enemies",
    "Part III: How to Win People to Your Way of Thinking — Ch.3: If You're Wrong, Admit It",
    "Part III: How to Win People to Your Way of Thinking — Ch.4: A Drop of Honey",
    "Part III: How to Win People to Your Way of Thinking — Ch.5: The Secret of Socrates",
    "Part III: How to Win People to Your Way of Thinking — Ch.6: The Safety Valve in Handling Complaints",
    "Part III: How to Win People to Your Way of Thinking — Ch.7: How to Get Cooperation",
    "Part III: How to Win People to Your Way of Thinking — Ch.8: A Formula That Will Work Wonders",
    "Part III: How to Win People to Your Way of Thinking — Ch.9: What Everybody Wants",
    "Part III: How to Win People to Your Way of Thinking — Ch.10: An Appeal That Everybody Likes",
    "Part III: How to Win People to Your Way of Thinking — Ch.11: The Movies Do It. TV Does It.",
    "Part III: How to Win People to Your Way of Thinking — Ch.12: When Nothing Else Works, Try This",
    "Part IV: Be a Leader — Ch.1: If You Must Find Fault, This Is the Way to Begin",
    "Part IV: Be a Leader — Ch.2: How to Criticize — and Not Be Hated for It",
    "Part IV: Be a Leader — Ch.3: Talk About Your Own Mistakes First",
    "Part IV: Be a Leader — Ch.4: No One Likes to Take Orders",
    "Part IV: Be a Leader — Ch.5: Let the Other Person Save Face",
    "Part IV: Be a Leader — Ch.6: How to Spur People On to Success",
    "Part IV: Be a Leader — Ch.7: Give a Dog a Good Name",
    "Part IV: Be a Leader — Ch.8: Make the Fault Seem Easy to Correct",
    "Part IV: Be a Leader — Ch.9: Making People Glad to Do What You Want",
  ],

  "think and grow rich": [
    "Preface: The Man Who Thought His Way to Riches",
    "Ch.1: Introduction — The Man Who 'Thought' His Way into Partnership",
    "Ch.2: Desire — The Starting Point of All Achievement",
    "Ch.3: Faith — Visualization of and Belief in the Attainment of Desire",
    "Ch.4: Auto-Suggestion — The Medium for Influencing the Subconscious Mind",
    "Ch.5: Specialized Knowledge — Personal Experiences or Observations",
    "Ch.6: Imagination — The Workshop of the Mind",
    "Ch.7: Organized Planning — The Crystallization of Desire into Action",
    "Ch.8: Decision — The Mastery of Procrastination",
    "Ch.9: Persistence — The Sustained Effort Necessary to Induce Faith",
    "Ch.10: Power of the Master Mind — The Driving Force",
    "Ch.11: The Mystery of Sex Transmutation",
    "Ch.12: The Subconscious Mind — The Connecting Link",
    "Ch.13: The Brain — A Broadcasting and Receiving Station for Thought",
    "Ch.14: The Sixth Sense — The Door to the Temple of Wisdom",
    "Ch.15: How to Outwit the Six Ghosts of Fear",
  ],

  "7 habits of highly effective people": [
    "Part One: Paradigms and Principles — Introduction",
    "Part One: Paradigms and Principles — Ch.1: Inside-Out",
    "Part Two: Private Victory — Ch.2: Habit 1 — Be Proactive",
    "Part Two: Private Victory — Ch.3: Habit 2 — Begin with the End in Mind",
    "Part Two: Private Victory — Ch.4: Habit 3 — Put First Things First",
    "Part Three: Public Victory — Ch.5: Habit 4 — Think Win/Win",
    "Part Three: Public Victory — Ch.6: Habit 5 — Seek First to Understand",
    "Part Three: Public Victory — Ch.7: Habit 6 — Synergize",
    "Part Four: Renewal — Ch.8: Habit 7 — Sharpen the Saw",
    "Part Four: Renewal — Inside-Out Again",
  ],

  "atomic habits": [
    "Introduction: My Story",
    "Part I: The Fundamentals — Ch.1: The Surprising Power of Atomic Habits",
    "Part I: The Fundamentals — Ch.2: How Your Habits Shape Your Identity",
    "Part I: The Fundamentals — Ch.3: How to Build Better Habits in 4 Simple Steps",
    "Part II: The 1st Law — Ch.4: The Man Who Didn't Look Right",
    "Part II: The 1st Law — Ch.5: The Best Way to Start a New Habit",
    "Part II: The 1st Law — Ch.6: Motivation Is Overrated",
    "Part II: The 1st Law — Ch.7: The Secret to Self-Control",
    "Part III: The 2nd Law — Ch.8: How to Make a Habit Irresistible",
    "Part III: The 2nd Law — Ch.9: The Role of Family and Friends",
    "Part III: The 2nd Law — Ch.10: How to Find and Fix the Causes of Your Bad Habits",
    "Part IV: The 3rd Law — Ch.11: Walk Slowly, but Never Backward",
    "Part IV: The 3rd Law — Ch.12: The Law of Least Effort",
    "Part IV: The 3rd Law — Ch.13: How to Stop Procrastinating",
    "Part IV: The 3rd Law — Ch.14: How to Make Good Habits Inevitable",
    "Part V: The 4th Law — Ch.15: The Cardinal Rule of Behavior Change",
    "Part V: The 4th Law — Ch.16: How to Stick with Good Habits Every Day",
    "Part V: The 4th Law — Ch.17: How an Accountability Partner Can Change Everything",
    "Advanced Tactics — Ch.18: The Truth About Talent",
    "Advanced Tactics — Ch.19: The Goldilocks Rule",
    "Advanced Tactics — Ch.20: The Downside of Creating Good Habits",
    "Conclusion: The Secret to Results That Last",
  ],

  "deep work": [
    "Introduction",
    "Part I: The Idea — Ch.1: Deep Work Is Valuable",
    "Part I: The Idea — Ch.2: Deep Work Is Rare",
    "Part I: The Idea — Ch.3: Deep Work Is Meaningful",
    "Part II: The Rules — Rule 1: Work Deeply",
    "Part II: The Rules — Rule 2: Embrace Boredom",
    "Part II: The Rules — Rule 3: Quit Social Media",
    "Part II: The Rules — Rule 4: Drain the Shallows",
    "Conclusion",
  ],

  // ─────────────────────────────────────────────
  // ECONOMICS & POLITICAL PHILOSOPHY
  // ─────────────────────────────────────────────
  "road to serfdom": [
    "Foreword by Milton Friedman",
    "Preface to the 1944 Edition",
    "Ch.1: The Abandoned Road",
    "Ch.2: The Great Utopia",
    "Ch.3: Individualism and Collectivism",
    "Ch.4: The 'Inevitability' of Planning",
    "Ch.5: Planning and Democracy",
    "Ch.6: Planning and the Rule of Law",
    "Ch.7: Economic Control and Totalitarianism",
    "Ch.8: Who, Whom?",
    "Ch.9: Security and Freedom",
    "Ch.10: Why the Worst Get on Top",
    "Ch.11: The End of Truth",
    "Ch.12: The Socialist Roots of Nazism",
    "Ch.13: The Totalitarians in Our Midst",
    "Ch.14: Material Conditions and Ideal Ends",
    "Ch.15: The Prospects of International Order",
    "Conclusion",
  ],

  "wealth of nations": [
    "Book I, Introduction and Plan",
    "Book I, Ch.1: The Division of Labour",
    "Book I, Ch.2: The Principle of Division — Exchange",
    "Book I, Ch.3: The Division of Labour Is Limited by the Extent of Market",
    "Book I, Ch.4: The Origin and Use of Money",
    "Book I, Ch.5: The Real and Nominal Price of Commodities",
    "Book I, Ch.6: Component Parts of the Price of Commodities",
    "Book I, Ch.7: Natural and Market Price",
    "Book I, Ch.8: The Wages of Labour",
    "Book I, Ch.9: Profits of Stock",
    "Book I, Ch.10: Wages and Profits in Different Employments",
    "Book I, Ch.11: Rent of Land",
    "Book II, Introduction: Stocks",
    "Book II, Ch.1: Division of Stock",
    "Book II, Ch.2: Money Considered as a Branch of General Stock",
    "Book II, Ch.3: The Accumulation of Capital",
    "Book II, Ch.4: Stock Lent at Interest",
    "Book II, Ch.5: Different Employments of Capitals",
    "Book III: Of the Different Progress of Opulence in Different Nations",
    "Book IV: Systems of Political Economy",
    "Book V: Revenue of the Sovereign or Commonwealth",
  ],

  capital: [
    "Preface to the First Edition",
    "Part I: Commodities and Money — Ch.1: The Commodity",
    "Part I: Commodities and Money — Ch.2: The Process of Exchange",
    "Part I: Commodities and Money — Ch.3: Money",
    "Part II: The Transformation of Money into Capital — Ch.4: The General Formula for Capital",
    "Part II: The Transformation of Money into Capital — Ch.5: Contradictions in the General Formula",
    "Part II: The Transformation of Money into Capital — Ch.6: The Buying and Selling of Labour-Power",
    "Part III: The Production of Absolute Surplus-Value — Ch.7: The Labour Process and the Valorisation Process",
    "Part III: The Production of Absolute Surplus-Value — Ch.8: Constant Capital and Variable Capital",
    "Part III: The Production of Absolute Surplus-Value — Ch.9: The Rate of Surplus-Value",
    "Part III: The Production of Absolute Surplus-Value — Ch.10: The Working Day",
    "Part III: The Production of Absolute Surplus-Value — Ch.11: The Rate and Mass of Surplus-Value",
    "Part IV: Production of Relative Surplus-Value — Ch.12: The Concept of Relative Surplus-Value",
    "Part IV: Production of Relative Surplus-Value — Ch.13: Co-operation",
    "Part IV: Production of Relative Surplus-Value — Ch.14: Division of Labour and Manufacture",
    "Part IV: Production of Relative Surplus-Value — Ch.15: Machinery and Large-Scale Industry",
    "Part V: The Production of Absolute and Relative Surplus-Value — Ch.16: Absolute and Relative Surplus-Value",
    "Part V: The Production of Absolute and Relative Surplus-Value — Ch.17: Changes of Magnitude in the Price of Labour-Power",
    "Part VI: Wages — Ch.18: The Transformation of the Value of Labour-Power into Wages",
    "Part VI: Wages — Ch.19: The Time-Wage",
    "Part VI: Wages — Ch.20: The Piece-Wage",
    "Part VI: Wages — Ch.21: National Differences in Wages",
    "Part VII: The Process of Accumulation of Capital — Ch.22: Simple Reproduction",
    "Part VII: The Process of Accumulation of Capital — Ch.23: Simple Reproduction on an Extended Scale",
    "Part VII: The Process of Accumulation of Capital — Ch.24: The So-Called Primitive Accumulation",
    "Part VII: The Process of Accumulation of Capital — Ch.25: The Modern Theory of Colonisation",
  ],

  "communist manifesto": [
    "Preface to the 1872 German Edition",
    "Preface to the 1882 Russian Edition",
    "Preface to the 1883 German Edition",
    "Preface to the 1888 English Edition",
    "Section I: Bourgeois and Proletarians",
    "Section II: Proletarians and Communists",
    "Section III: Socialist and Communist Literature",
    "Section IV: Position of the Communists in Relation to the Various Existing Opposition Parties",
  ],

  // ─────────────────────────────────────────────
  // PSYCHOLOGY / FREUD
  // ─────────────────────────────────────────────
  "civilization and its discontents": [
    "Ch.1: The Oceanic Feeling and the Origins of Religion",
    "Ch.2: The Purpose of Life and the Pleasure Principle",
    "Ch.3: Unhappiness and the Sources of Suffering",
    "Ch.4: The Origins of Civilization",
    "Ch.5: The Erotic and the Destructive Impulses",
    "Ch.6: Civilized Sexuality and Neurosis",
    "Ch.7: The Sense of Guilt",
    "Ch.8: The Death Instinct and the Future of Civilization",
  ],

  "interpretation of dreams": [
    "Preface",
    "Ch.1: The Scientific Literature on Dreams",
    "Ch.2: The Method of Dream Interpretation",
    "Ch.3: A Dream Is a Wish Fulfilment",
    "Ch.4: The Distortion in Dreams",
    "Ch.5: The Material and Sources of Dreams",
    "Ch.6: The Dream-Work",
    "Ch.7: The Psychology of Dream Processes",
  ],

  // ─────────────────────────────────────────────
  // BUSINESS & PRODUCTIVITY
  // ─────────────────────────────────────────────
  "good to great": [
    "Preface",
    "Ch.1: Good Is the Enemy of Great",
    "Ch.2: Level 5 Leadership",
    "Ch.3: First Who... Then What",
    "Ch.4: Confront the Brutal Facts",
    "Ch.5: The Hedgehog Concept",
    "Ch.6: A Culture of Discipline",
    "Ch.7: Technology Accelerators",
    "Ch.8: The Flywheel and the Doom Loop",
    "Ch.9: From Good to Great to Built to Last",
    "Epilogue: Living with the Great Questions",
  ],

  "zero to one": [
    "Preface",
    "Ch.1: The Challenge of the Future",
    "Ch.2: Party Like It's 1999",
    "Ch.3: All Happy Companies Are Different",
    "Ch.4: The Ideology of Competition",
    "Ch.5: Last Mover Advantage",
    "Ch.6: You Are Not a Lottery Ticket",
    "Ch.7: Follow the Money",
    "Ch.8: Secrets",
    "Ch.9: Foundations",
    "Ch.10: The Mechanics of Mafia",
    "Ch.11: If You Build It, Will They Come?",
    "Ch.12: Man and Machine",
    "Ch.13: Seeing Green",
    "Ch.14: The Founder's Paradox",
    "Conclusion: Stagnation or Singularity?",
  ],

  "lean startup": [
    "Introduction",
    "Part One: Vision — Ch.1: Start",
    "Part One: Vision — Ch.2: Define",
    "Part One: Vision — Ch.3: Learn",
    "Part One: Vision — Ch.4: Experiment",
    "Part Two: Steer — Ch.5: Leap",
    "Part Two: Steer — Ch.6: Test",
    "Part Two: Steer — Ch.7: Measure",
    "Part Two: Steer — Ch.8: Pivot (or Persevere)",
    "Part Three: Accelerate — Ch.9: Batch",
    "Part Three: Accelerate — Ch.10: Grow",
    "Part Three: Accelerate — Ch.11: Adapt",
    "Part Three: Accelerate — Ch.12: Innovate",
    "Epilogue: Waste Not",
    "Join the Movement",
  ],

  principles: [
    "Introduction",
    "Part I: Where I'm Coming From — Ch.1: My Call to Adventure",
    "Part I: Where I'm Coming From — Ch.2: Crossing the Threshold",
    "Part I: Where I'm Coming From — Ch.3: My Abyss",
    "Part I: Where I'm Coming From — Ch.4: My Road of Trials",
    "Part I: Where I'm Coming From — Ch.5: The Ultimate Boon",
    "Part I: Where I'm Coming From — Ch.6: Returning the Boon",
    "Part I: Where I'm Coming From — Ch.7: My Last Year",
    "Part II: Life Principles — Ch.1: Embrace Reality and Deal with It",
    "Part II: Life Principles — Ch.2: Use the 5-Step Process",
    "Part II: Life Principles — Ch.3: Be Radically Open-Minded",
    "Part II: Life Principles — Ch.4: Understand That People Are Wired Differently",
    "Part II: Life Principles — Ch.5: Learn How to Make Decisions Effectively",
    "Summary and Table of Life Principles",
    "Part III: Work Principles — Introduction to Work Principles",
    "Part III: Work Principles — To Get the Culture Right",
    "Part III: Work Principles — To Get the People Right",
    "Part III: Work Principles — To Build and Evolve Your Machine",
    "Summary and Table of Work Principles",
  ],

  "psychology of money": [
    "Introduction: The Greatest Show on Earth",
    "Ch.1: No One's Crazy",
    "Ch.2: Luck and Risk",
    "Ch.3: Never Enough",
    "Ch.4: Confounding Compounding",
    "Ch.5: Getting Wealthy vs. Staying Wealthy",
    "Ch.6: Tails, You Win",
    "Ch.7: Freedom",
    "Ch.8: Man in the Car Paradox",
    "Ch.9: Wealth Is What You Don't See",
    "Ch.10: Save Money",
    "Ch.11: Reasonable > Rational",
    "Ch.12: Surprise!",
    "Ch.13: Room for Error",
    "Ch.14: You'll Change",
    "Ch.15: Nothing's Free",
    "Ch.16: You and Me",
    "Ch.17: The Seduction of Pessimism",
    "Ch.18: When You'll Believe Anything",
    "Ch.19: All Together Now",
    "Ch.20: Confessions",
    "Postscript: A Brief History of Why the U.S. Consumer Thinks the Way They Do",
  ],

  "intelligent investor": [
    "Preface by Warren Buffett",
    "Introduction: What This Book Expects to Accomplish",
    "Ch.1: Investment vs. Speculation",
    "Ch.2: The Investor and Inflation",
    "Ch.3: A Century of Stock Market History",
    "Ch.4: General Portfolio Policy — The Defensive Investor",
    "Ch.5: The Defensive Investor and Common Stocks",
    "Ch.6: Portfolio Policy for the Enterprising Investor — The Negative Approach",
    "Ch.7: Portfolio Policy for the Enterprising Investor — The Positive Side",
    "Ch.8: The Investor and Market Fluctuations — Mr. Market",
    "Ch.9: Investing in Investment Funds",
    "Ch.10: The Investor and His Advisers",
    "Ch.11: Security Analysis for the Lay Investor",
    "Ch.12: Things to Consider About Per-Share Earnings",
    "Ch.13: A Comparison of Four Listed Companies",
    "Ch.14: Stock Selection for the Defensive Investor",
    "Ch.15: Stock Selection for the Enterprising Investor",
    "Ch.16: Convertible Issues and Warrants",
    "Ch.17: Four Extremely Instructive Case Histories",
    "Ch.18: A Comparison of Eight Pairs of Companies",
    "Ch.19: Shareholders and Managements",
    "Ch.20: 'Margin of Safety' as the Central Concept",
    "Epilogue",
  ],

  "poor charlies almanack": [
    "Introduction by Peter Kaufman",
    "Part I: A Portrait of Charles T. Munger",
    "Part II: The Talks — Talk 1: Harvard School Commencement Speech",
    "Part II: The Talks — Talk 2: A Lesson on Elementary Worldly Wisdom",
    "Part II: The Talks — Talk 3: A Lesson on Elementary Worldly Wisdom, Revisited",
    "Part II: The Talks — Talk 4: Practical Thought About Practical Thinking",
    "Part II: The Talks — Talk 5: The Psychology of Human Misjudgment",
    "Part II: The Talks — Talk 6: The Basic Framework for Investment",
    "Part II: The Talks — Talk 7: Academic Economics",
    "Part II: The Talks — Talk 8: Art Investment",
    "Part II: The Talks — Talk 9: Breakfast Meeting of the Philanthropy Roundtable",
    "Part II: The Talks — Talk 10: USC Gould School of Law Commencement Address",
    "Part III: Munger's Investment Vehicles",
    "Part IV: The Munger Network of Mental Models",
    "Appendix: Charlie Munger's Reading List",
  ],
  // ─────────────────────────────────────────────
  // CLASSIC FICTION & LITERATURE (continued)
  // ─────────────────────────────────────────────
  "the stranger": [
    "Part I — Ch.1: The Telegram and the Funeral",
    "Part I — Ch.2: Marie and the Beach",
    "Part I — Ch.3: Salamano and Raymond",
    "Part I — Ch.4: Raymond's Letter",
    "Part I — Ch.5: Sunday in the Apartment",
    "Part I — Ch.6: The Beach and the Arab — The Shot",
    "Part II — Ch.1: Interrogation and the Lawyer",
    "Part II — Ch.2: The Examining Magistrate",
    "Part II — Ch.3: Prison and Marie's Visit",
    "Part II — Ch.4: The Trial Begins",
    "Part II — Ch.5: The Verdict",
    "Part II — Ch.6: The Chaplain and the Final Acceptance",
  ],

  metamorphosis: [
    "Part I: The Transformation and Its Immediate Aftermath",
    "Part II: Family Adaptation and Gregor's Decline",
    "Part III: The Lodgers, Grete's Revolt, and Gregor's Death",
    "Epilogue: The Family's Liberation",
  ],
  "lord of the flies": [
    "Ch.1: The Sound of the Shell",
    "Ch.2: Fire on the Mountain",
    "Ch.3: Huts on the Beach",
    "Ch.4: Painted Faces and Long Hair",
    "Ch.5: Beast from Water",
    "Ch.6: Beast from Air",
    "Ch.7: Shadows and Tall Trees",
    "Ch.8: Gift for the Darkness",
    "Ch.9: A View to a Death",
    "Ch.10: The Shell and the Glasses",
    "Ch.11: Castle Rock",
    "Ch.12: Cry of the Hunters",
  ],

  "the alchemist": [
    "Prologue: Narcissus",
    "Part I — The Boy Santiago and His Dream",
    "Part I — The Merchant of Crystals",
    "Part I — The Old King Melchizedek and the Soul of the World",
    "Part II — The Caravan and the Desert",
    "Part II — The Oasis and Fatima",
    "Part II — The Alchemist Appears",
    "Part II — The Language of the World",
    "Part II — The Wind, the Sun, and the Soul of the World",
    "Part II — The Pyramids and the Treasure",
    "Epilogue: The Return",
  ],

  "the kite runner": [
    "Ch.1: Introduction and Rahim Khan's Call",
    "Ch.2: Amir and Hassan — Childhood in Kabul",
    "Ch.3: Baba's Character and the Pomegranate Tree",
    "Ch.4: Reading to Hassan",
    "Ch.5: Ali's Past and Hassan's Harelip",
    "Ch.6: The Kite Tournament",
    "Ch.7: The Rape — The Alley",
    "Ch.8: The Winter After the Tournament",
    "Ch.9: Betrayal — The Watch and Money",
    "Ch.10: Ali and Hassan Leave",
    "Ch.11: America — Fremont, California",
    "Ch.12: The Flea Market and Soraya",
    "Ch.13: The Wedding and Baba's Death",
    "Ch.14: The Call from Rahim Khan",
    "Ch.15: Pakistan — Rahim Khan's Story",
    "Ch.16: Hassan's Life After Kabul",
    "Ch.17: Hassan's Letter and the Truth",
    "Ch.18: The Decision to Return",
    "Ch.19: Crossing into Afghanistan",
    "Ch.20: Kabul Under the Taliban",
    "Ch.21: The Orphanage and Assef",
    "Ch.22: The Fight — For You a Thousand Times Over",
    "Ch.23: Recovery in Pakistan",
    "Ch.24: Sohrab in America",
    "Ch.25: The Kite Flying — Redemption",
  ],

  // ─────────────────────────────────────────────
  // PHILOSOPHY (continued)
  // ─────────────────────────────────────────────
  "the prince": [
    "Dedication to Lorenzo de' Medici",
    "Ch.1: Types of Principalities",
    "Ch.2: Hereditary Principalities",
    "Ch.3: Mixed Principalities",
    "Ch.4: How Alexander's Conquests Were Held",
    "Ch.5: How to Govern Conquered Cities",
    "Ch.6: New Principalities Won by Arms and Ability",
    "Ch.7: New Principalities Won by Fortune and Foreign Arms",
    "Ch.8: Principalities Won by Crime",
    "Ch.9: The Civil Principality",
    "Ch.10: How All Principalities Should Be Measured",
    "Ch.11: Ecclesiastical Principalities",
    "Ch.12: Different Kinds of Soldiers",
    "Ch.13: Auxiliary, Mixed, and Native Soldiers",
    "Ch.14: A Prince's Duty Concerning Military Affairs",
    "Ch.15: The Things for Which Men Are Praised or Blamed",
    "Ch.16: Generosity and Parsimony",
    "Ch.17: Cruelty and Mercy — Is It Better to Be Loved or Feared?",
    "Ch.18: How Princes Should Keep Their Word",
    "Ch.19: Avoiding Hatred and Contempt",
    "Ch.20: Fortresses and Other Expedients",
    "Ch.21: How a Prince Should Act to Win Honor",
    "Ch.22: The Prince's Ministers",
    "Ch.23: How to Avoid Flatterers",
    "Ch.24: Why Italian Princes Have Lost Their States",
    "Ch.25: Fortune and Free Will",
    "Ch.26: Exhortation to Liberate Italy",
  ],

  // ─────────────────────────────────────────────
  // SELF-HELP / PERSONAL DEVELOPMENT (continued)
  // ─────────────────────────────────────────────
  "the 7 habits of highly effective people": [
    "Introduction: Inside-Out",
    "Part I: Paradigms and Principles",
    "Part II — Habit 1: Be Proactive",
    "Part II — Habit 2: Begin with the End in Mind",
    "Part II — Habit 3: Put First Things First",
    "Part III — Habit 4: Think Win/Win",
    "Part III — Habit 5: Seek First to Understand, Then to Be Understood",
    "Part III — Habit 6: Synergize",
    "Part IV — Habit 7: Sharpen the Saw",
    "Part V: Inside-Out Again",
  ],

  // ─────────────────────────────────────────────
  // SCIENCE & PSYCHOLOGY
  // ─────────────────────────────────────────────
  "guns germs and steel": [
    "Prologue: Yali's Question",
    "Ch.1: Up to the Starting Line",
    "Ch.2: A Natural Experiment of History",
    "Ch.3: Collision at Cajamarca",
    "Part II — Ch.4: Farmer Power",
    "Part II — Ch.5: History's Haves and Have-Nots",
    "Part II — Ch.6: To Farm or Not to Farm",
    "Part II — Ch.7: How to Make an Almond",
    "Part II — Ch.8: Why Did Wild Plants Become Domesticated?",
    "Part II — Ch.9: Zebras, Unhappy Marriages, and the Anna Karenina Principle",
    "Part II — Ch.10: Spacious Skies and Tilted Axes",
    "Part III — Ch.11: Lethal Gift of Livestock",
    "Part III — Ch.12: Blueprints and Borrowed Letters",
    "Part III — Ch.13: Necessity's Mother",
    "Part III — Ch.14: From Egalitarianism to Kleptocracy",
    "Part IV — Ch.15: Yali's People",
    "Part IV — Ch.16: How China Became Chinese",
    "Part IV — Ch.17: Speedboat to Polynesia",
    "Part IV — Ch.18: Hemispheres Colliding",
    "Part IV — Ch.19: How Africa Became Black",
    "Part IV — Ch.20: Who Are the Japanese?",
    "Epilogue: The Future of Human History as a Science",
  ],

  educated: [
    "Preface",
    "Part I — Ch.1: End of Days",
    "Part I — Ch.2: The Midwife",
    "Part I — Ch.3: Cream Cheese",
    "Part I — Ch.4: Apache Women",
    "Part I — Ch.5: Honest Dirt",
    "Part I — Ch.6: Shield and Buckler",
    "Part I — Ch.7: The Lord Will Provide",
    "Part I — Ch.8: Choices",
    "Part I — Ch.9: Perfect in His Generations",
    "Part I — Ch.10: Shield and Buckler II",
    "Part II — Ch.11: Instinct",
    "Part II — Ch.12: Fish Eyes",
    "Part II — Ch.13: Silence in the Church",
    "Part II — Ch.14: My Feet No Longer Touch Earth",
    "Part II — Ch.15: No Longer Bound",
    "Part II — Ch.16: Wrenching Away",
    "Part II — Ch.17: To Keep It Holy",
    "Part II — Ch.18: Blood and Feathers",
    "Part II — Ch.19: In the Beginning, God Made Adam",
    "Part II — Ch.20: Recitativo",
    "Part III — Ch.21: Skullcap",
    "Part III — Ch.22: What We Whispered and What We Screamed",
    "Part III — Ch.23: I'm from Idaho",
    "Part III — Ch.24: A Knight, Errant",
    "Part III — Ch.25: The Substance of Things",
    "Part III — Ch.26:Ack",
    "Part III — Ch.27: If I Were a Woman",
    "Part III — Ch.28: Pygmalion",
    "Part III — Ch.29: Graduation",
    "Part III — Ch.30: Tragedy Then Farce",
    "Part III — Ch.31: Tragedy Then Farce II",
    "Part III — Ch.32: Nightshade",
    "Part III — Ch.33: Sorcery",
    "Part III — Ch.34: Heal Thyself",
    "Part III — Ch.35: West of the Sun",
    "Epilogue",
  ],
  "how to invest": [
    "Introduction: What Investing Is All About",
    "Ch.1: Fixed Income — Larry Fink (BlackRock)",
    "Ch.2: Public Equities — Ron Baron & John W. Rogers Jr.",
    "Ch.3: Real Estate — Jon Gray (Blackstone) & Sam Zell",
    "Ch.4: Private Wealth / Family Offices — Mary Callahan Erdoes (J.P. Morgan) & Dawn Fitzpatrick (Soros Fund Management)",
    "Ch.5: Endowments — Paula Volent (Rockefeller University) & Kim Lew (Columbia Investment Management)",
    "Ch.6: Hedge Funds — Seth Klarman (Baupost), Ray Dalio (Bridgewater), Stan Druckenmiller (Duquesne), Jim Simons (Renaissance Technologies) & John Paulson",
    "Ch.7: Private Equity and Buyouts — Sandra Horbach (Carlyle) & Orlando Bravo (Thoma Bravo)",
    "Ch.8: Distressed Debt — Bruce Karsh (Oaktree Capital Management)",
    "Ch.9: Venture Capital — Marc Andreessen (Andreessen Horowitz) & Michael Moritz (Sequoia Capital)",
    "Ch.10: Cryptocurrencies — Mike Novogratz (Galaxy Digital)",
    "Ch.11: SPACs — Betsy Cohen",
    "Ch.12: Infrastructure — Adebayo Ogunlesi (Global Infrastructure Partners)",
    "Ch.13: ESG — David Blood (Generation Investment Management)",
    "Conclusion: What Makes a Great Investor",
  ],
};

/**
 * Normalize a book title for lookup: lowercase, remove leading articles,
 * remove punctuation, collapse whitespace.
 */
function normalizeTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/^(the |a |an )/, "")
    .replace(/[^a-z0-9\s]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Lookup the chapter list for a book.
 * Tries exact normalized match first, then partial containment matching.
 * Returns null if no match found.
 */
export function lookupBookChapters(bookName: string): string[] | null {
  const normalized = normalizeTitle(bookName);

  // 1. Exact match
  if (BOOK_KNOWLEDGE_BASE[normalized]) {
    return BOOK_KNOWLEDGE_BASE[normalized];
  }

  // 2. Partial match: input contains key or key contains input
  const keys = Object.keys(BOOK_KNOWLEDGE_BASE);
  for (const key of keys) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return BOOK_KNOWLEDGE_BASE[key];
    }
  }

  // 3. Word-overlap match (at least 60% of query words appear in key)
  const queryWords = normalized.split(" ").filter((w) => w.length > 2);
  if (queryWords.length > 0) {
    let bestKey = "";
    let bestScore = 0;
    for (const key of keys) {
      const matches = queryWords.filter((w) => key.includes(w)).length;
      const score = matches / queryWords.length;
      if (score > bestScore) {
        bestScore = score;
        bestKey = key;
      }
    }
    if (bestScore >= 0.6 && bestKey) {
      return BOOK_KNOWLEDGE_BASE[bestKey];
    }
  }

  return null;
}

/**
 * Parse a raw book file (full text or table of contents) to extract
 * chapter/part headings.
 *
 * Detection order (highest confidence first):
 *  1. Explicit TOC block: lines between "contents" / "table of contents" header
 *     and the first long prose paragraph
 *  2. PART I/II/III + Chapter N patterns anywhere in the text
 *  3. Numbered lists: "1. Title", "1) Title"
 *  4. Keyword chapter lines: lines starting with "chapter", "section", "part"
 *
 * Returns a flat array of chapter title strings (may be empty).
 */
export function parseBookFileContent(text: string): string[] {
  const lines = text
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);

  const chapters: string[] = [];
  let currentPart = "";

  // ── Step 1: Look for a Table of Contents block ──────────────────────────────
  // Find the TOC header line index
  const tocHeaderIdx = lines.findIndex((l) =>
    /^(table of contents|contents|t\.?o\.?c\.?)$/i.test(l),
  );

  if (tocHeaderIdx !== -1) {
    // Collect lines after the TOC header until we hit a long prose line (>120 chars)
    // or a clear body section marker
    const tocLines = lines.slice(tocHeaderIdx + 1);
    for (const line of tocLines) {
      if (line.length > 120) break; // prose paragraph → end of TOC
      if (
        /^(preface|foreword|introduction to the|about the author)/i.test(
          line,
        ) &&
        line.length > 40
      )
        break;

      // Part header inside TOC
      const partMatch = line.match(/^PART\s+([IVXLCDM\d]+)[.:)\s]+(.*)/i);
      if (partMatch) {
        currentPart = `Part ${partMatch[1].toUpperCase()}: ${partMatch[2].trim()}`;
        continue;
      }

      // Numbered chapter line (may have page numbers at end)
      const numMatch = line.match(/^(\d+)[.)\s]+(.+?)(?:\s{2,}\d+)?$/);
      if (numMatch) {
        const rawTitle = numMatch[2].replace(/\s+\d+$/, "").trim();
        if (rawTitle.length < 3) continue;
        const title = currentPart
          ? `${currentPart} — Ch.${numMatch[1]}: ${rawTitle}`
          : `Chapter ${numMatch[1]}: ${rawTitle}`;
        chapters.push(title);
        continue;
      }

      // Roman numeral chapter
      const romanMatch = line.match(
        /^([ivxlcdmIVXLCDM]{1,7})[.)\s]+(.+?)(?:\s{2,}\d+)?$/i,
      );
      if (romanMatch) {
        const rawTitle = romanMatch[2].replace(/\s+\d+$/, "").trim();
        if (rawTitle.length < 3) continue;
        const title = currentPart
          ? `${currentPart} — ${romanMatch[1].toUpperCase()}. ${rawTitle}`
          : `${romanMatch[1].toUpperCase()}. ${rawTitle}`;
        chapters.push(title);
        continue;
      }

      // Plain titled line (all-caps or Title Case, short enough to be a heading)
      if (line.length <= 80 && /^[A-Z]/.test(line) && !/[.!?]$/.test(line)) {
        // Skip if it looks like a continuation (no digits and very short)
        if (line.split(" ").length >= 2 || /chapter|part|section/i.test(line)) {
          const title = currentPart ? `${currentPart} — ${line}` : line;
          chapters.push(title);
        }
      }
    }
    if (chapters.length >= 3) return chapters;
  }

  // ── Step 2: Scan full text for chapter/part patterns ────────────────────────
  currentPart = "";
  for (const line of lines) {
    if (line.length > 120) continue; // skip prose

    const partMatch = line.match(/^PART\s+([IVXLCDM\d]+)[.:)\s]+(.*)/i);
    if (partMatch) {
      const partLabel = partMatch[1].toUpperCase();
      const partTitle = partMatch[2].trim();
      currentPart = `Part ${partLabel}: ${partTitle}`;
      continue;
    }

    // "Chapter N: Title" or "Chapter N — Title" or "Chapter N Title"
    const chapterKeyMatch = line.match(
      /^chapter\s+(\d+|[ivxlcdmIVXLCDM]+)[.:)\s–—-]+(.+)/i,
    );
    if (chapterKeyMatch) {
      const num = chapterKeyMatch[1];
      const rawTitle = chapterKeyMatch[2].replace(/\s+\d+$/, "").trim();
      if (rawTitle.length < 2) continue;
      const title = currentPart
        ? `${currentPart} — Ch.${num}: ${rawTitle}`
        : `Chapter ${num}: ${rawTitle}`;
      if (!chapters.includes(title)) chapters.push(title);
      continue;
    }

    // Numbered list: "1. Title" or "1) Title"
    const numMatch = line.match(/^(\d{1,2})[.)\s]+(.+?)(?:\s{2,}\d+)?$/);
    if (numMatch) {
      const rawTitle = numMatch[2].replace(/\s+\d+$/, "").trim();
      if (rawTitle.length < 4 || /^\d+$/.test(rawTitle)) continue;
      const title = currentPart
        ? `${currentPart} — Ch.${numMatch[1]}: ${rawTitle}`
        : `Chapter ${numMatch[1]}: ${rawTitle}`;
      if (!chapters.includes(title)) chapters.push(title);
    }
  }

  return chapters;
}
