/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BookPlan = IDL.Record({
  'id' : IDL.Nat,
  'bookName' : IDL.Text,
  'bookType' : IDL.Text,
  'dailyReadingHours' : IDL.Nat,
  'timestamp' : Time,
  'generatedPlan' : IDL.Text,
});

export const idlService = IDL.Service({
  'createBookPlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deletePlan' : IDL.Func([IDL.Nat], [], []),
  'fetchBookChapters' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllPlans' : IDL.Func([], [IDL.Vec(BookPlan)], ['query']),
  'getPlan' : IDL.Func([IDL.Nat], [BookPlan], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BookPlan = IDL.Record({
    'id' : IDL.Nat,
    'bookName' : IDL.Text,
    'bookType' : IDL.Text,
    'dailyReadingHours' : IDL.Nat,
    'timestamp' : Time,
    'generatedPlan' : IDL.Text,
  });
  
  return IDL.Service({
    'createBookPlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deletePlan' : IDL.Func([IDL.Nat], [], []),
    'fetchBookChapters' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllPlans' : IDL.Func([], [IDL.Vec(BookPlan)], ['query']),
    'getPlan' : IDL.Func([IDL.Nat], [BookPlan], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
